### ISSUE TITLE
Week 3 Review

### ISSUE THREAD

**Issue by BartMassey** [Nirdeshika/ExportBrowserHistory#1]
Good. Give more detail about the proposed function in the README. I'd probably just name the project ExportBrowserHistory and be done with it: shorter and avoids the possible trademark issue.

**Comment by Nirdeshika** [comment]
Sure Professor, I will rename the project and download it as csv to be more generic.
I am not sure I understand what you meant by "Give more detail about the proposed function in the README". Could you please elaborate?

**Comment by BartMassey** [comment]
I get the general idea, but what are the details of how it will work? What can I and others expect to see when it's working?

**Comment by Nirdeshika** [comment]
Yeah. That makes sense. I added two new sections: How the project works and Details on how to use it. Could you please look at it and let me know if it is sufficient or do I need to make any further changes?

**Comment by BartMassey** [comment]
Looks fine. Thanks.
